version: '3.8'

services:
  rustapp:
    container_name: rust
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=some-redis
      - REDIS_PASSWORD=p23askdf490jkls
      - REIDS_PORT=6379
    image: redis:latest